### PR TITLE
Add italian translation

### PR DESCRIPTION
**Pull request by pagurobunny**
Add italian translation

### CODE REVIEW

**Comment by donadigo** [comment]
Hm, why did you close this? I haven't got around to reviewing some of these branches yet.

**Comment by pagurobunny** [comment]
Hello,
I'm not a programmer, I wanted to translate AppEditor into Italian, but I don't know how Github works. It's the first time for me. Sorry for how I write in English, use Google Translate.

**Comment by donadigo** [comment]
Okay, no problem - thanks for your help! I will review this in a bit.

**Comment by pagurobunny** [comment]
Thank you,
if I learn how to do it, I would also like to translate Eddy.

**Pull request closed without merging**
